CST-241-deploy-app
Ecosystem-Assessments/eDriversApp pull request #3
Opened 2024-01-30 20:28 UTC by SteveViss

@KevCaz, quand tu auras quelques minutes, juste jeter un coup d'oeil sur la structure et les fichiers en lien avec le déploiement, voir si tu aimes ca!

2024-01-30 20:29 UTC, SteveViss reviewed
Tu peux discard le commit 3f60346 qui est juste un remaniement des fichiers

2024-01-31 16:35 UTC, KevCaz requested changes

2024-01-31 16:35 UTC, KevCaz commented on Dockerfile
> +FROM rocker/shiny:latest
lock version

2024-01-31 16:35 UTC, KevCaz commented on Dockerfile
> +RUN Rscript -e "remotes::install_deps('/srv/shiny-server/')"
golem style please

2024-01-31 16:35 UTC, KevCaz commented on shiny-server.conf
> +  listen 5000;
checker pourquoi 5000

2024-01-31 16:35 UTC, KevCaz commented on shiny-server.conf
> +# Define a server that listens on port 3838
changer 3838

2024-01-31 16:35 UTC, KevCaz commented on shiny-server.sh
> +Rscript -e "shiny::runApp(port = 5000, host = '0.0.0.0')" >> /var/log/shiny-server.log 2>&1
Retirer la redirection vers le var/log

2024-02-01 13:38 UTC, SteveViss commented on Dockerfile
> +FROM rocker/shiny:latest
Done

2024-02-01 13:43 UTC, SteveViss commented on Dockerfile
> +RUN Rscript -e "remotes::install_deps('/srv/shiny-server/')"
Done

2024-02-01 13:55 UTC, SteveViss commented on shiny-server.conf
> +  listen 5000;
Ca pourrait être n'importe quoi, faut juste éviter les ports réservé. Voici la liste: https://en.wikipedia.org/wiki/List_of_TCP_and_UDP_port_numbers. Ceux qui sont connus évoluent entre 0 et 1023

2024-02-01 13:58 UTC, SteveViss commented on shiny-server.sh
> +Rscript -e "shiny::runApp(port = 5000, host = '0.0.0.0')" >> /var/log/shiny-server.log 2>&1
Retrait du /var/log. C'est journaliser dans le cloud. L'image étant reboot à chaque appel vers l'instance, les logs ne sont pas conservés dans l'image.

2024-02-01 15:30 UTC, KevCaz approved these changes

2024-02-01 15:31 UTC, merged